<?php

return [
    'client_id' => env('HUBSPOT_CLIENT_ID'),
    'client_secret' => env('HUBSPOT_CLIENT_SECRET'),
    'redirect_uri' => env('HUBSPOT_REDIRECT_URI', env('APP_URL').'/settings/integrations/hubspot/callback'),
    'authorize_url' => 'https://app.hubspot.com/oauth/authorize',
    'token_url' => 'https://api.hubapi.com/oauth/v1/token',
    'api_base' => env('HUBSPOT_API_BASE', 'https://api.hubapi.com'),
    'scopes' => [
        'oauth',
        'crm.objects.contacts.read',
        'crm.objects.contacts.write',
        'crm.objects.companies.read',
        'crm.objects.companies.write',
        'crm.objects.deals.read',
        'crm.objects.deals.write',
        'crm.objects.owners.read',
        'crm.objects.quotes.read',
        'crm.objects.quotes.write',
        'crm.objects.line_items.read',
        'crm.objects.line_items.write',
        'crm.objects.leads.read',
        'crm.objects.leads.write',
        'crm.objects.orders.read',
        'crm.objects.invoices.read',
        'crm.objects.subscriptions.read',
        'crm.objects.custom.read',
        'crm.objects.custom.write',
        'crm.schemas.contacts.read',
        'crm.schemas.companies.read',
        'crm.schemas.deals.read',
        'crm.schemas.custom.read',
        'crm.schemas.custom.write',
        'crm.lists.read',
        'crm.lists.write',
        'crm.import',
        'crm.export',
        'tickets',
        'timeline',
        'e-commerce',
        'forms',
        'forms-uploaded-files',
        'files',
        'files.ui_hidden.read',
        'content',
        'cms.domains.read',
        'cms.domains.write',
        'communication_preferences.read',
        'communication_preferences.write',
        'communication_preferences.read_write',
        'conversations.read',
        'conversations.write',
        'sales-email-read',
        'automation',
        'actions',
        'settings.users.read',
        'settings.users.write',
        'account-info.security.read',
        'collector.graphql_query.execute',
        'collector.graphql_schema.read',
    ],
    'optional_scopes' => [
        'social',
        'ads.read',
        'business-intelligence',
        'integration-sync',
        'marketing.campaigns.read',
        'marketing.campaigns.write',
    ],
];
